server:
  shutdown: graceful
management:
  server:
    port: 9000
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true